---
- name: test CICD pipeline project
  hosts: dev
  become: True #Rootuser
  tasks:
    - name: Download Java JRE
      get_url:
        url: http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jre-8u60-linux-x64.rpm
        dest: /opt/jre-8u60-linux-x64.rpm
        headers: 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
    - name: install Java JRE rpm from a local file
      yum:
        name: /opt/jre-8u60-linux-x64.rpm
        state: present
    - name: Download Java JDK
      get_url:
        url: http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.rpm
        dest: /opt/jdk-8u60-linux-x64.rpm
        headers: 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
    - name: Install Java JDK rpm from a local file
      yum:
        name: /opt/jdk-8u60-linux-x64.rpm
        state: present
    - name: install python pip 
      yum: 
        name: python-pip
        state: present
    - name: install docker
      yum: 
        name: docker
        state: present
    - name: start docker
      service: 
        name: docker
        state: started
        enabled: yes    
    - name: install docker-py module
      service:
        name: docker-py
        state: present
    - name: Start the container from docker image
      docker_container:
        name: testpipeine
        image: "jav160696/testpipeine:latest"
        state: started
        ports:
        - 0.0.0.0:8080:8080
